baseURL = "https://one-bit.net/"
languageCode = "ja-jp"
title = "ONE-BIT"
theme = "minimal"
googleAnalytics = "UA-129664753-1"

[params]
    author = "Calin Tataru"
    description = "広島市安佐南区で活動しているプログラミングクラブです"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/calendar/"
    name = "開催カレンダー"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "ブログ"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "このサイトについて"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:pclub.onebit@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/kaneyasusatoshi"
    name = "facebook"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/pclub_one_bit"
    name = "twitter"
    weight = 3

