theme="amp"
baseurl = "https://one-bit.net"
title = "ONE-BIT"
copyright = "© 2018 Copyright ONE-BIT"
canonifyurls = true

[params]
  description = "広島市安佐南区で活動しているプログラミングクラブです" #optional
  googleanalytics = "UA-129664753-1" # optional

# optional
[social]
  twitter = "@club_one_bit"
  facebook = "kaneyasusatoshi"